-- DATABASE MIGRATION V2 - Mipaymaster
-- Description: Transition to Locked Payroll Architecture
-- Generated by: Antigravity
-- Date: 2026-01-19

SET FOREIGN_KEY_CHECKS = 0;

-- =======================================================
-- 1. UTILITY: SAFE RENAME PROCEDURE
-- =======================================================
DROP PROCEDURE IF EXISTS SafeMigrationRename;
DELIMITER //
CREATE PROCEDURE SafeMigrationRename(IN old_tbl VARCHAR(64), IN new_tbl VARCHAR(64))
BEGIN
    DECLARE db_name VARCHAR(64);
    SELECT DATABASE() INTO db_name;
    
    -- Check if source table exists
    IF EXISTS (
        SELECT * 
        FROM information_schema.TABLES 
        WHERE TABLE_SCHEMA = db_name 
        AND TABLE_NAME = old_tbl
    ) THEN
        -- Check if target table ALREADY exists
        IF NOT EXISTS (
            SELECT * 
            FROM information_schema.TABLES 
            WHERE TABLE_SCHEMA = db_name 
            AND TABLE_NAME = new_tbl
        ) THEN
            SET @s = CONCAT('RENAME TABLE `', old_tbl, '` TO `', new_tbl, '`');
            PREPARE stmt FROM @s;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
        END IF;
    END IF;
END //
DELIMITER ;

-- =======================================================
-- 2. DEPRECATION (SAFE MIGRATION)
-- =======================================================
-- Renaming existing tables to _legacy to preserve data references
-- while freeing up names for the new strict architecture.

CALL SafeMigrationRename('salary_categories', 'salary_categories_legacy');
CALL SafeMigrationRename('employees', 'employees_legacy');
CALL SafeMigrationRename('payroll_runs', 'payroll_runs_legacy');
CALL SafeMigrationRename('payslips', 'payslips_legacy');
CALL SafeMigrationRename('statutory_settings', 'statutory_settings_legacy');
-- Bonus: Rename other related tables that might conflict or are obsolete
CALL SafeMigrationRename('salary_structures', 'salary_structures_legacy'); 
CALL SafeMigrationRename('attendance_records', 'attendance_records_legacy');

DROP PROCEDURE SafeMigrationRename;

-- =======================================================
-- 3. NEW SCHEMA IMPLEMENTATION
-- =======================================================

-- A. COMPANY MODULE
-- Ensuring strict schema for companies. 
-- If table exists (wasn't renamed), we alter/ensure columns.
CREATE TABLE IF NOT EXISTS companies (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    phone VARCHAR(50),
    address TEXT,
    currency VARCHAR(10) DEFAULT 'NGN',
    tax_jurisdiction VARCHAR(50) DEFAULT 'Nigeria',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- B. DEPARTMENTS
CREATE TABLE IF NOT EXISTS departments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    company_id INT NOT NULL,
    name VARCHAR(100) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE
);

-- C. SALARY CATEGORIES (Structure Only)
CREATE TABLE IF NOT EXISTS salary_categories (
    id INT AUTO_INCREMENT PRIMARY KEY,
    company_id INT NOT NULL,
    title VARCHAR(100) NOT NULL,
    base_gross_amount DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE
);

-- E. SALARY COMPONENTS (Global Single Source)
CREATE TABLE IF NOT EXISTS salary_components (
    id INT AUTO_INCREMENT PRIMARY KEY,
    company_id INT NOT NULL,
    name VARCHAR(100) NOT NULL,
    type ENUM('basic', 'system', 'allowance') NOT NULL,
    default_percentage DECIMAL(5, 2) DEFAULT 0.00,
    is_taxable BOOLEAN DEFAULT TRUE,
    is_pensionable BOOLEAN DEFAULT TRUE,
    is_active BOOLEAN DEFAULT TRUE,
    is_custom BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE
);

-- D. SALARY CATEGORY BREAKDOWN
-- Links categories to components with specific percentages.
-- Enforces: Total percentage per category MUST equal 100% (Application Level Validation Required)
CREATE TABLE IF NOT EXISTS salary_category_breakdown (
    id INT AUTO_INCREMENT PRIMARY KEY,
    category_id INT NOT NULL,
    salary_component_id INT NOT NULL, -- FK to Component
    component_name VARCHAR(100) NOT NULL, -- Snapshot/Display Name
    percentage DECIMAL(5, 2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (category_id) REFERENCES salary_categories(id) ON DELETE CASCADE,
    FOREIGN KEY (salary_component_id) REFERENCES salary_components(id) ON DELETE RESTRICT
);

-- F. EMPLOYEES
CREATE TABLE IF NOT EXISTS employees (
    id INT AUTO_INCREMENT PRIMARY KEY,
    company_id INT NOT NULL,
    department_id INT,
    category_id INT,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    status ENUM('active', 'terminated', 'suspended') DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
    FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE SET NULL,
    FOREIGN KEY (category_id) REFERENCES salary_categories(id) ON DELETE SET NULL
);

-- G. EMPLOYEE SALARY OVERRIDES (Increments)
CREATE TABLE IF NOT EXISTS employee_salary_adjustments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    employee_id INT NOT NULL,
    adjustment_type ENUM('fixed', 'percentage', 'override') NOT NULL,
    adjustment_value DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    effective_from DATE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE
);

-- H. BONUSES & DEDUCTIONS
CREATE TABLE IF NOT EXISTS payroll_bonus_types (
    id INT AUTO_INCREMENT PRIMARY KEY,
    company_id INT NOT NULL,
    name VARCHAR(100) NOT NULL,
    calculation_mode ENUM('fixed', 'percentage') NOT NULL,
    percentage_base ENUM('basic', 'gross') DEFAULT 'gross',
    is_active BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS payroll_deduction_types (
    id INT AUTO_INCREMENT PRIMARY KEY,
    company_id INT NOT NULL,
    name VARCHAR(100) NOT NULL,
    calculation_mode ENUM('fixed', 'percentage') NOT NULL,
    percentage_base ENUM('basic', 'gross') DEFAULT 'gross',
    is_active BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE
);

-- I. STATUTORY SETTINGS
CREATE TABLE IF NOT EXISTS statutory_settings (
    company_id INT PRIMARY KEY,
    enable_paye BOOLEAN DEFAULT TRUE,
    enable_pension BOOLEAN DEFAULT TRUE,
    enable_nhis BOOLEAN DEFAULT FALSE,
    enable_nhf BOOLEAN DEFAULT FALSE,
    pension_employer_percentage DECIMAL(5, 2) DEFAULT 10.00,
    pension_employee_percentage DECIMAL(5, 2) DEFAULT 8.00,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE
);

-- J. PAYROLL RUNS
CREATE TABLE IF NOT EXISTS payroll_runs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    company_id INT NOT NULL,
    period_month INT NOT NULL,
    period_year INT NOT NULL,
    status ENUM('draft', 'approved', 'paid') DEFAULT 'draft',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
    UNIQUE KEY unique_run (company_id, period_month, period_year)
);

-- K. PAYROLL SHEET (FINAL OUTPUT)
CREATE TABLE IF NOT EXISTS payroll_entries (
    id INT AUTO_INCREMENT PRIMARY KEY,
    payroll_run_id INT NOT NULL,
    employee_id INT NOT NULL,
    gross_salary DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    total_allowances DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    total_deductions DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    net_pay DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (payroll_run_id) REFERENCES payroll_runs(id) ON DELETE CASCADE,
    FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE
);

-- =======================================================
-- 4. SEEDING & DATA MIGRATION
-- =======================================================

-- 4.1 Seed Default Components for existing Companies
-- Assuming companies table was preserved and has IDs.
INSERT IGNORE INTO salary_components (company_id, name, type, default_percentage, is_active, is_custom)
SELECT id, 'Basic Salary', 'basic', 40.00, 1, 0 FROM companies;

INSERT IGNORE INTO salary_components (company_id, name, type, default_percentage, is_active, is_custom)
SELECT id, 'Housing Allowance', 'allowance', 30.00, 1, 0 FROM companies;

INSERT IGNORE INTO salary_components (company_id, name, type, default_percentage, is_active, is_custom)
SELECT id, 'Transport Allowance', 'allowance', 20.00, 1, 0 FROM companies;

-- 4.2 Seed Statutory Settings
INSERT INTO statutory_settings (company_id, enable_paye, enable_pension, pension_employer_percentage, pension_employee_percentage)
SELECT id, 1, 1, 10.00, 8.00 FROM companies
ON DUPLICATE KEY UPDATE company_id=company_id;

-- 4.3 Migrate Clean Employee Data from Legacy
-- We only migrate basic identity. Categories/Dept must be re-assigned.
INSERT INTO employees (company_id, first_name, last_name, email, status, created_at)
SELECT 
    company_id, 
    first_name, 
    last_name, 
    email, 
    'active', 
    created_at 
FROM employees_legacy 
WHERE company_id IN (SELECT id FROM companies);

-- End of Migration
SET FOREIGN_KEY_CHECKS = 1;
